spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false
        hbm2ddl:
          auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

riot:
  api:
    key: RGAPI-2ff553e3-202d-4755-a8a4-29bed95a3c0a

